cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED ARCHIVE_DIR OR ARCHIVE_DIR STREQUAL "")
  message(FATAL_ERROR "Set ARCHIVE_DIR to a build-local download directory")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/inputs.cmake")
file(MAKE_DIRECTORY "${ARCHIVE_DIR}")
foreach(name IN LISTS VOVE_JXL_INPUTS)
  set(archive "${ARCHIVE_DIR}/${name}-${${name}_commit}.tar.gz")
  if(NOT EXISTS "${archive}")
    file(DOWNLOAD "https://codeload.github.com/${${name}_repository}/tar.gz/${${name}_commit}"
      "${archive}" EXPECTED_HASH "SHA256=${${name}_sha256}" TLS_VERIFY ON)
  endif()
  file(SHA256 "${archive}" actual)
  if(NOT actual STREQUAL "${${name}_sha256}")
    message(FATAL_ERROR "SHA256 mismatch: ${archive}")
  endif()
  message(STATUS "Verified ${name}: ${actual}")
endforeach()
