cmake_minimum_required(VERSION 3.25)
foreach(required PREFIX BUILD_ROOT)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
function(expect_cache key expected)
  file(STRINGS "${BUILD_ROOT}/CMakeCache.txt" entry REGEX "^${key}:[^=]*=" LIMIT_COUNT 1)
  string(REGEX REPLACE "^[^=]*=" "" actual "${entry}")
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Expected ${key}=${expected}, got '${actual}'")
  endif()
endfunction()
foreach(option BOXES TRANSCODE_JPEG TOOLS DEVTOOLS BENCHMARK EXAMPLES FUZZERS JNI
    SJPEG OPENEXR SKCMS VIEWERS PLUGINS DOXYGEN MANPAGES TCMALLOC COVERAGE LTO)
  expect_cache(JPEGXL_ENABLE_${option} OFF)
endforeach()
foreach(option BUILD_SHARED_LIBS BUILD_TESTING PROVISION_DEPENDENCIES
    JPEGXL_BUNDLE_LIBPNG JPEGXL_TEST_TOOLS HWY_ENABLE_CONTRIB HWY_ENABLE_EXAMPLES
    HWY_ENABLE_TESTS BROTLI_BUILD_TOOLS BROTLI_BUILD_FOR_PACKAGE)
  expect_cache(${option} OFF)
endforeach()
expect_cache(JPEGXL_FORCE_SYSTEM_LCMS2 ON)
expect_cache(HWY_FORCE_STATIC_LIBS ON)
foreach(required lib/libjxl_dec.a lib/libjxl_cms.a lib/libhwy.a
    include/jxl/decode.h include/jxl/cms.h
    lib/cmake/vove-jpegxl-decode/vove-jpegxl-decode-config.cmake
    vove-jpegxl-decode-manifest.txt)
  if(NOT EXISTS "${PREFIX}/${required}")
    message(FATAL_ERROR "Missing staged file: ${required}")
  endif()
endforeach()
file(GLOB_RECURSE build_archives "${BUILD_ROOT}/build/*.a")
foreach(archive IN LISTS build_archives)
  if(NOT archive MATCHES "/lib(jxl_dec|jxl_cms|hwy)\\.a$")
    message(FATAL_ERROR "Unexpected built archive: ${archive}")
  endif()
endforeach()
file(GLOB_RECURSE files LIST_DIRECTORIES FALSE "${PREFIX}/*")
set(total 0)
foreach(path IN LISTS files)
  file(SIZE "${path}" bytes)
  math(EXPR total "${total} + ${bytes}")
  if(path MATCHES "\\.(dll|exe|so|dylib)$" OR path MATCHES "/libjxl\\.a$")
    message(FATAL_ERROR "Unexpected installed tool, shared library or full encoder library: ${path}")
  endif()
  if(path MATCHES "\\.a$" AND NOT path MATCHES "/lib(jxl_dec|jxl_cms|hwy)\\.a$")
    message(FATAL_ERROR "Unexpected staged archive: ${path}")
  endif()
endforeach()
message(STATUS "JPEG XL decoder-only prefix: ${total} bytes; jxl_dec + jxl_cms + hwy, external reused LCMS2")
