#pragma once

// Generated by scripts/generate_catalog_tool_artwork.py.
// Authored points, centered on the ring; PDF Y points upward.
// ViewAll.ai: SHA-256 f2adf66e5fc6a58a56e37e7c398ddfc9dd15a80276fbc5132318bc9906f85065
// f5.ai: SHA-256 e0bb6fc9520c9f06051b24333c48df25e7118b876a2538803ba1fb5b29bc2ca1

#include <QColor>
#include <QPainterPath>

#include <array>

namespace vove::ui::artwork {

inline const std::array<QPainterPath, 5> &catalog_eye_paths() {
    static const auto paths = [] {
        std::array<QPainterPath, 5> result;
        result[0].setFillRule(Qt::WindingFill);
        result[0].moveTo(0, 10.7085);
        result[0].cubicTo(5.905, 10.7085, 10.708, 5.9045, 10.708, 0.0005);
        result[0].cubicTo(10.708, -5.9045, 5.905, -10.7085, 0, -10.7085);
        result[0].cubicTo(-5.905, -10.7085, -10.708, -5.9045, -10.708, 0.0005);
        result[0].cubicTo(-10.708, 5.9045, -5.905, 10.7085, 0, 10.7085);
        result[0].closeSubpath();
        result[1].setFillRule(Qt::WindingFill);
        result[1].moveTo(0, 9.2915);
        result[1].cubicTo(-5.123, 9.2915, -9.292, 5.1235, -9.292, -0.0005);
        result[1].cubicTo(-9.292, -5.1235, -5.123, -9.2915, 0, -9.2915);
        result[1].cubicTo(5.123, -9.2915, 9.292, -5.1235, 9.292, -0.0005);
        result[1].cubicTo(9.292, 5.1235, 5.123, 9.2915, 0, 9.2915);
        result[1].closeSubpath();
        result[2].setFillRule(Qt::WindingFill);
        result[2].moveTo(6.9756, 0.2609);
        result[2].cubicTo(6.9756, -3.0721, 4.2736, -5.7741, 0.9406, -5.7741);
        result[2].cubicTo(-2.3934, -5.7741, -5.0954, -3.0721, -5.0954, 0.2609);
        result[2].cubicTo(-5.0954, 3.5939, -2.3934, 6.2959, 0.9406, 6.2959);
        result[2].cubicTo(4.2736, 6.2959, 6.9756, 3.5939, 6.9756, 0.2609);
        result[2].closeSubpath();
        result[3].setFillRule(Qt::WindingFill);
        result[3].moveTo(4.3883, 0.2609);
        result[3].cubicTo(4.3883, -1.6431, 2.8443, -3.1871, 0.9403, -3.1871);
        result[3].cubicTo(-0.9637, -3.1871, -2.5077, -1.6431, -2.5077, 0.2609);
        result[3].cubicTo(-2.5077, 2.1649, -0.9637, 3.7089, 0.9403, 3.7089);
        result[3].cubicTo(2.8443, 3.7089, 4.3883, 2.1649, 4.3883, 0.2609);
        result[3].closeSubpath();
        result[4].setFillRule(Qt::WindingFill);
        result[4].moveTo(5.2491, 2.6834);
        result[4].cubicTo(5.2491, 1.4934, 4.2841, 0.5294, 3.0951, 0.5294);
        result[4].cubicTo(1.9051, 0.5294, 0.9401, 1.4934, 0.9401, 2.6834);
        result[4].cubicTo(0.9401, 3.8734, 1.9051, 4.8374, 3.0951, 4.8374);
        result[4].cubicTo(4.2841, 4.8374, 5.2491, 3.8734, 5.2491, 2.6834);
        result[4].closeSubpath();
        return result;
    }();
    return paths;
}

// white, vanilla, blue, dark_gray; passive then hover in each pair.
inline constexpr std::array<std::array<QRgb, 5>, 8> catalog_eye_inks{{
    {{qRgb(178, 178, 178), qRgb(242, 242, 242), qRgb(91, 91, 91), qRgb(178, 178, 178), qRgb(242, 242, 242)}},
    {{qRgb(91, 91, 91), qRgb(242, 242, 242), qRgb(255, 127, 0), qRgb(91, 169, 179), qRgb(242, 242, 242)}},
    {{qRgb(142, 179, 193), qRgb(241, 228, 187), qRgb(91, 169, 179), qRgb(142, 179, 193), qRgb(241, 228, 187)}},
    {{qRgb(91, 169, 179), qRgb(241, 228, 187), qRgb(255, 127, 0), qRgb(91, 169, 179), qRgb(241, 228, 187)}},
    {{qRgb(142, 179, 193), qRgb(241, 228, 187), qRgb(91, 169, 179), qRgb(82, 106, 112), qRgb(241, 228, 187)}},
    {{qRgb(91, 169, 179), qRgb(241, 228, 187), qRgb(255, 127, 0), qRgb(91, 169, 179), qRgb(241, 228, 187)}},
    {{qRgb(91, 91, 91), qRgb(178, 178, 178), qRgb(91, 91, 91), qRgb(51, 51, 51), qRgb(178, 178, 178)}},
    {{qRgb(91, 91, 91), qRgb(178, 178, 178), qRgb(255, 127, 0), qRgb(93, 165, 181), qRgb(242, 242, 242)}},
}};

inline const std::array<QPainterPath, 3> &catalog_refresh_paths() {
    static const auto paths = [] {
        std::array<QPainterPath, 3> result;
        result[0].setFillRule(Qt::WindingFill);
        result[0].moveTo(10.7085, 0);
        result[0].cubicTo(10.7085, 5.905, 5.9045, 10.708, -0.0005, 10.708);
        result[0].cubicTo(-1.5575, 10.708, -3.0335, 10.367, -4.3695, 9.767);
        result[0].lineTo(-3.3595, 9.469);
        result[0].lineTo(-3.6295, 8.552);
        result[0].cubicTo(-2.5145, 9.028, -1.2875, 9.292, -0.0005, 9.292);
        result[0].cubicTo(5.1235, 9.292, 9.2915, 5.123, 9.2915, 0);
        result[0].cubicTo(9.2915, -1.977, 8.6665, -3.808, 7.6085, -5.314);
        result[0].lineTo(6.3265, -3.849);
        result[0].lineTo(6.0645, -7.798);
        result[0].lineTo(10.0135, -8.06);
        result[0].lineTo(8.5575, -6.398);
        result[0].cubicTo(9.9005, -4.612, 10.7085, -2.403, 10.7085, 0);
        result[0].closeSubpath();
        result[0].moveTo(4.6951, -8.004);
        result[0].cubicTo(3.3151, -8.817, 1.7131, -9.291, -0.0009, -9.291);
        result[0].cubicTo(-5.1239, -9.291, -9.2919, -5.123, -9.2919, 0);
        result[0].cubicTo(-9.2919, 2.435, -8.3359, 4.641, -6.7959, 6.297);
        result[0].lineTo(-5.7889, 4.707);
        result[0].lineTo(-4.9219, 8.569);
        result[0].lineTo(-8.7839, 9.435);
        result[0].lineTo(-7.5749, 7.527);
        result[0].cubicTo(-9.5019, 5.591, -10.7089, 2.941, -10.7089, 0);
        result[0].cubicTo(-10.7089, -5.905, -5.9049, -10.708, -0.0009, -10.708);
        result[0].cubicTo(2.1051, -10.708, 4.0651, -10.089, 5.7231, -9.035);
        result[0].lineTo(4.6261, -8.955);
        result[0].closeSubpath();
        result[1].setFillRule(Qt::WindingFill);
        result[1].moveTo(-5.328, -4.6345);
        result[1].quadTo(-5.328, -4.7305, -5.424, -4.7305);
        result[1].lineTo(-5.628, -4.7305);
        result[1].quadTo(-5.724, -4.7305, -5.724, -4.6345);
        result[1].lineTo(-5.724, 4.4615);
        result[1].quadTo(-5.724, 4.5575, -5.628, 4.5575);
        result[1].lineTo(-0.444, 4.5575);
        result[1].quadTo(-0.336, 4.5575, -0.336, 4.4615);
        result[1].lineTo(-0.336, 4.2695);
        result[1].quadTo(-0.336, 4.1735, -0.444, 4.1735);
        result[1].lineTo(-5.328, 4.1735);
        result[1].lineTo(-5.328, 0.1655);
        result[1].lineTo(-0.96, 0.1655);
        result[1].quadTo(-0.852, 0.1655, -0.852, 0.0695);
        result[1].lineTo(-0.852, -0.1225);
        result[1].quadTo(-0.852, -0.2185, -0.96, -0.2185);
        result[1].lineTo(-5.328, -0.2185);
        result[1].closeSubpath();
        result[1].moveTo(1.62, 0.2855);
        result[1].quadTo(2.052, 0.7055, 2.664, 0.9515);
        result[1].quadTo(3.276, 1.1975, 3.984, 1.1975);
        result[1].quadTo(4.86, 1.1975, 5.502, 0.8195);
        result[1].quadTo(6.144, 0.4415, 6.504, -0.2365);
        result[1].quadTo(6.864, -0.9145, 6.864, -1.8385);
        result[1].quadTo(6.864, -2.7505, 6.498, -3.4405);
        result[1].quadTo(6.132, -4.1305, 5.478, -4.5205);
        result[1].quadTo(4.824, -4.9105, 3.96, -4.9105);
        result[1].quadTo(3.24, -4.9105, 2.604, -4.6225);
        result[1].quadTo(1.968, -4.3345, 1.512, -3.7645);
        result[1].quadTo(1.056, -3.1945, 0.876, -2.3785);
        result[1].quadTo(0.864, -2.2705, 0.936, -2.2465);
        result[1].lineTo(1.116, -2.1985);
        result[1].quadTo(1.236, -2.1745, 1.248, -2.2585);
        result[1].quadTo(1.56, -3.4225, 2.292, -3.9625);
        result[1].quadTo(3.024, -4.5025, 3.96, -4.5025);
        result[1].quadTo(4.68, -4.5025, 5.244, -4.1845);
        result[1].quadTo(5.808, -3.8665, 6.126, -3.2665);
        result[1].quadTo(6.444, -2.6665, 6.444, -1.8385);
        result[1].quadTo(6.444, -0.6265, 5.784, 0.0815);
        result[1].quadTo(5.124, 0.7895, 3.984, 0.7895);
        result[1].quadTo(3.216, 0.7895, 2.562, 0.4775);
        result[1].quadTo(1.908, 0.1655, 1.452, -0.4225);
        result[1].quadTo(1.38, -0.4945, 1.308, -0.4585);
        result[1].lineTo(1.26, -0.4345);
        result[1].quadTo(1.188, -0.3985, 1.188, -0.3265);
        result[1].lineTo(1.62, 4.4615);
        result[1].quadTo(1.62, 4.5575, 1.74, 4.5575);
        result[1].lineTo(6.36, 4.5575);
        result[1].quadTo(6.456, 4.5575, 6.456, 4.4615);
        result[1].lineTo(6.456, 4.2695);
        result[1].quadTo(6.456, 4.1735, 6.36, 4.1735);
        result[1].lineTo(1.992, 4.1735);
        result[1].closeSubpath();
        result[2].setFillRule(Qt::WindingFill);
        result[2].moveTo(-5.7123, -4.8745);
        result[2].quadTo(-5.8563, -4.8745, -5.8563, -4.7305);
        result[2].lineTo(-5.8563, 4.3055);
        result[2].quadTo(-5.8563, 4.4375, -5.7123, 4.4375);
        result[2].lineTo(-0.2883, 4.4375);
        result[2].quadTo(-0.1443, 4.4375, -0.1443, 4.3055);
        result[2].lineTo(-0.1443, 3.5735);
        result[2].quadTo(-0.1443, 3.4295, -0.2883, 3.4295);
        result[2].lineTo(-4.7883, 3.4295);
        result[2].lineTo(-4.7883, 0.2255);
        result[2].lineTo(-0.8283, 0.2255);
        result[2].quadTo(-0.6963, 0.2255, -0.6963, 0.0935);
        result[2].lineTo(-0.6963, -0.6385);
        result[2].quadTo(-0.6963, -0.7825, -0.8283, -0.7825);
        result[2].lineTo(-4.7883, -0.7825);
        result[2].lineTo(-4.7883, -4.7305);
        result[2].quadTo(-4.7883, -4.8745, -4.9323, -4.8745);
        result[2].closeSubpath();
        result[2].moveTo(4.2357, -4.8145);
        result[2].quadTo(3.0717, -4.8145, 2.1897, -4.1545);
        result[2].quadTo(1.3077, -3.4945, 0.9957, -2.2825);
        result[2].quadTo(0.9597, -2.1625, 1.0797, -2.1265);
        result[2].lineTo(1.7997, -1.9465);
        result[2].quadTo(1.9197, -1.9105, 1.9557, -2.0305);
        result[2].quadTo(2.2317, -2.9185, 2.8257, -3.3445);
        result[2].quadTo(3.4197, -3.7705, 4.1877, -3.7705);
        result[2].quadTo(5.1117, -3.7705, 5.6877, -3.2125);
        result[2].quadTo(6.2637, -2.6545, 6.2637, -1.6825);
        result[2].quadTo(6.2637, -0.7105, 5.7057, -0.1405);
        result[2].quadTo(5.1477, 0.4295, 4.1877, 0.4295);
        result[2].quadTo(2.9637, 0.4295, 2.0037, -0.5425);
        result[2].quadTo(1.8957, -0.6145, 1.8117, -0.5665);
        result[2].lineTo(1.4157, -0.3865);
        result[2].quadTo(1.3197, -0.3265, 1.3317, -0.2185);
        result[2].lineTo(1.7517, 4.5455);
        result[2].quadTo(1.7877, 4.6775, 1.8957, 4.6775);
        result[2].lineTo(6.7677, 4.6775);
        result[2].quadTo(6.8997, 4.6775, 6.8997, 4.5455);
        result[2].lineTo(6.8997, 3.8135);
        result[2].quadTo(6.8997, 3.6695, 6.7677, 3.6695);
        result[2].lineTo(2.5917, 3.6695);
        result[2].lineTo(2.2917, 0.5735);
        result[2].quadTo(3.1557, 1.3655, 4.4517, 1.3655);
        result[2].quadTo(5.3157, 1.3655, 5.9697, 0.9815);
        result[2].quadTo(6.6237, 0.5975, 6.9897, -0.0865);
        result[2].quadTo(7.3557, -0.7705, 7.3557, -1.6945);
        result[2].quadTo(7.3557, -2.6185, 6.9597, -3.3205);
        result[2].quadTo(6.5637, -4.0225, 5.8617, -4.4185);
        result[2].quadTo(5.1597, -4.8145, 4.2357, -4.8145);
        result[2].closeSubpath();
        return result;
    }();
    return paths;
}

// white, vanilla, blue, dark_gray; passive then hover in each pair.
inline const std::array<std::array<QColor, 3>, 8> catalog_refresh_inks{{
    {{QColor(178, 178, 178), QColor(91, 91, 91), QColor(0, 0, 0, 0)}},
    {{QColor(91, 91, 91), QColor(0, 0, 0, 0), QColor(255, 127, 0)}},
    {{QColor(93, 165, 181), QColor(4, 63, 97), QColor(0, 0, 0, 0)}},
    {{QColor(255, 127, 0), QColor(0, 0, 0, 0), QColor(33, 56, 64)}},
    {{QColor(241, 228, 187), QColor(41, 171, 226), QColor(0, 0, 0, 0)}},
    {{QColor(255, 127, 0), QColor(0, 0, 0, 0), QColor(241, 228, 187)}},
    {{QColor(91, 91, 91), QColor(178, 178, 178), QColor(0, 0, 0, 0)}},
    {{QColor(178, 178, 178), QColor(0, 0, 0, 0), QColor(255, 127, 0)}},
}};

} // namespace vove::ui::artwork
